FROM centos:7
RUN yum install -y epel-release
RUN yum install -y \
    git \
    gcc-c++ \
    xrootd-client \
    xrootd-client-devel \
    gdb \
    which \
    python-devel

RUN git clone https://github.com/xrootd/xrootd-python.git && \
    cd xrootd-python && \
    python setup.py install --install-lib=/usr/lib/python2.7/site-packages/
